export const JOURNAL_TITLES: Record<string, string> = {
  "3-tips-for-burning-fat": "3 Tips For Burning Fat",
  "3-travel-tips-for-staying-fit": "3 Travel Tips For Staying Fit",
  "4-ingredient-savory-pumpkin-slices": "4 Ingredient Savory Pumpkin Slices",
  "5-secrets-to-living-in-a-small-space": "5 Secrets To Living In A Small Space",
  "5-steps-to-a-healthy-lifestyle": "5 Steps To A Healthy Lifestyle",
  "5-things-you-should-say-to-every-pregnant-woman": "5 Things You Should Say To Every Pregnant Woman",
  "5-ways-to-create-physical-and-fun-activities-for-kids": "5 Ways To Create Physical And Fun Activities For Kids",
  "5-ways-to-find-inspiration": "5 Ways To Find Inspiration",
  "6-rules-for-traveling-parents-mom-edition": "6 Rules For Traveling Parents: Mom Edition",
  "a-day-of-photos": "A Day of Photos",
  "a-persons-a-person-no-matter-how-small-respecting-who-your-child-is": "A Person's A Person No Matter How Small: Respecting Who Your Child Is",
  "a-proper-thanksgiving-meal": "A Proper Thanksgiving Meal",
  "abs-and-stretch-marks": "Abs And Stretch Marks",
  "apples-and-peanut-butter": "Apples and Peanut Butter",
  "bean-and-amaranth-chili": "Bean And Amaranth Chili",
  "birth-and-postpartum-what-they-dont-tell-you": "Birth and Postpartum: What They Don't Tell You",
  "celebrate-the-small-things": "Celebrate The Small Things",
  "date-night": "Date Night",
  "entering-the-third-trimester": "Entering The Third Trimester",
  "even-toddlers-can-be-trustworthy": "Even Toddlers Can Be Trustworthy",
  "every-single-potty-training-mistake": "Every Single Potty Training Mistake",
  "exchanging-one-challenge-for-another": "Exchanging One Challenge For Another",
  "falling-in-love-with-your-kid": "Falling In Love With Your Kid",
  "family-and-internationals": "Family And Internationals",
  "foreign-fears": "Foreign Fears",
  "forgiving-a-toddler": "Forgiving A Toddler",
  "from-now-til-christmas": "From Now 'Til Christmas",
  "guilty-pregnancy-parenting": "Guilty Pregnancy Parenting",
  "hearty-healthy-beef-stew": "Hearty Healthy Beef Stew",
  "how-to-discipline-without-punishing": "How To Discipline Without Punishing",
  "how-to-find-balance-in-parenthood": "How To Find Balance In Parenthood",
  "i-let-my-baby-eat-dirt": "I Let My Baby Eat Dirt",
  "is-beauty-only-skin-deep": "Is Beauty Only Skin Deep?",
  "is-it-just-a-phase": "Is It Just A Phase?",
  "knowing-where-to-draw-the-line": "Knowing Where To Draw The Line",
  "learning-to-let-go-and-hold-onto": "Learning To Let Go And Hold Onto",
  "learning-to-take-a-moment": "Learning To Take A Moment",
  "low-fat-egg-salad": "Low Fat Egg Salad",
  "make-them-laugh": "Make Them Laugh",
  "mama-forgets": "Mama Forgets",
  "mom-identity": "Mom Identity",
  "motherhood-mantras": "Motherhood Mantras",
  "motherhood-ugly": "Motherhood Is Making Me Ugly",
  "my-birth-story-olivia-amelia-dolenc": "My Birth Story: Olivia Amelia Dolenc",
  "my-child-owes-me-nothing": "My Child Owes Me Nothing",
  "my-city-ljubljana": "My City, Ljubljana",
  "my-level-10": "My Level 10",
  "my-second-pregnancy": "My Second Pregnancy",
  "no-cookies-for-baby": "No Cookies For Baby",
  "practicing-immediate-forgiveness": "Practicing Immediate Forgiveness",
  "pregnancy-complications": "Pregnancy Complications",
  "pregnancy-differently": "4 Things I Would Have Done Differently During Pregnancy",
  "pregnancy-untold": "Pregnancy: What They Don't Tell You",
  "preparing-for-takeoff": "Preparing For Takeoff",
  "quinoa-bowl": "Quinoa Bowl",
  "recovering-from-birth-can-feel-traumatic": "Recovering From Birth Can Feel Traumatic",
  "rice-cake-sandwiches": "Open Chicken Rice Cake Sandwiches",
  "simple-things-to-help-you-get-pregnant": "Simple Things To Help You Get Pregnant",
  "sometimes-you-just-need-to-listen-and-thats-all": "Sometimes You Just Need To Listen... And That's All",
  "step-away-from-the-diet-and-into-a-new-you": "Step Away From The Diet And Into A New You",
  "step-away-from-the-vacuum": "Step Away From The Vacuum",
  "suffering-from-jet-lag": "Suffering From Jet Lag",
  "super-simple-stir-fry": "Super Simple Stir Fry",
  "thanksgiving": "Thanksgiving",
  "the-celebration-of-saint-nicholas": "The Celebration of Saint Nicholas",
  "the-gmo-debate": "The GMO Debate",
  "the-greatest-gift-you-can-give-your-child": "The Greatest Gift You Can Give Your Child",
  "the-netherlands-part-i": "The Netherlands, Part I",
  "the-netherlands-part-ii": "The Netherlands, Part II",
  "this-journal-is-ours": "This journal is ours",
  "veggie-tacos-and-homemade-spelt-tortillas": "Veggie Tacos and Homemade Spelt Tortillas",
  "what-if-my-child-makes-choices-i-dont-like": "What If My Child Makes Choices I Don't Like",
  "what-kids-say": "What Kids Say",
  "what-natural-labor-birth-feels-like": "What Natural Labor & Birth Feels Like",
  "when-you-lose-your-child": "When You Lose Your Child",
  "why-i-dont-want-my-kid-to-obey": "Why I Don't Want My Kid To Obey",
  "why-not-be-beautiful": "Why Not Be Beautiful",
};

export function journalTitle(slug: string): string {
  return JOURNAL_TITLES[slug] || slug;
}

export function journalPath(slug: string): string {
  return "/journal/" + slug;
}
